---
- name: 'Set JAVA_HOME if configured'
  ansible.builtin.template:
    src: 'java_home.sh.j2'
    dest: '/etc/profile.d/java_home.sh'
    mode: 0755
  when: java_home is defined and java_home
  become: true
