---
- name: 'RedHat | Configure the Amazon Corretto repository'
  when:
    - java_distribution == 'corretto' and
      ansible_distribution != 'Amazon'
  become: true
  block:
    - name: 'RedHat | Ensure the dependencies are installed'
      ansible.builtin.package:
        name: 'yum-utils'
        state: 'present'

    - name: 'RedHat | Add the Amazon Corretto repository'
      ansible.builtin.template:
        src: 'corretto.repo.j2'
        dest: '/etc/yum.repos.d/corretto.repo'
        owner: 'root'
        group: 'root'
        mode: 0644

- name: 'RedHat | Install the Java package'
  ansible.builtin.package:
    name: "{{ java_corretto_package_name
      if java_distribution == 'corretto' or
      ansible_distribution == 'Amazon'
      else java_openjdk_package_name }}"
    state: 'present'
  become: true
