---
- name: 'Load the Java OS-specific variables'
  ansible.builtin.include_vars: '{{ ansible_os_family }}.yml'

- name: 'Install the Java package'
  ansible.builtin.include_tasks: 'install-{{ ansible_os_family }}.yml'

- name: 'Configure the Java package'
  ansible.builtin.import_tasks: 'configure.yml'
