---
- name: 'Install Java package'
  ansible.builtin.include_tasks: "package/install-{{ ansible_facts['os_family'] }}.yml"
  when:
    - java_install_from == 'package' and
      ansible_facts['os_family'] in ['Debian', 'RedHat']

- name: 'Install Java binary'
  ansible.builtin.include_tasks: 'binary/install-{{ ansible_system }}.yml'
  when:
    - java_install_from == 'binary'

- name: 'Configure Java package'
  ansible.builtin.import_tasks: 'configure.yml'
