---
- name: 'Include OS-specific variables'
  ansible.builtin.include_vars: '{{ distribution }}'
  with_first_found:
    - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
    - '{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml'
  loop_control:
    loop_var: distribution

- name: 'Include OS-specific tasks for install packages'
  ansible.builtin.include_tasks: 'install-{{ ansible_os_family }}.yml'

- name: 'Include tasks for configure Java'
  ansible.builtin.import_tasks: 'configure.yml'
