---
- name: 'Load the Java OS-specific variables'
  ansible.builtin.include_vars: '{{ java_variables_file }}'
  with_first_found:
    - '{{ ansible_distribution }}.yml'
    - '{{ ansible_os_family }}.yml'
  loop_control:
    loop_var: java_variables_file

- name: 'Install the Java package'
  ansible.builtin.include_tasks: 'install-{{ ansible_os_family }}.yml'

- name: 'Configure the Java package'
  ansible.builtin.import_tasks: 'configure.yml'
