---
- name: 'Install Java {{ java_major_version }} package'
  ansible.builtin.include_tasks: "install-{{ ansible_facts['os_family'] }}.yml"

- name: 'Configure Java package'
  ansible.builtin.import_tasks: 'configure.yml'
