---
- name: 'Verify'
  hosts: all
  gather_facts: false

  tasks:
    - name: 'Check current Java version'
      ansible.builtin.command:
        cmd: java --version
      changed_when: false
      register: _java_version_check

    - name: 'Java version output'
      ansible.builtin.debug:
        msg: '{{ _java_version_check.stdout }}'
