---
- name: 'Verify'
  hosts: all
  gather_facts: false

  tasks:
    - name: 'Check the current Java version'
      ansible.builtin.command:
        cmd: 'java --version'
      changed_when: false
      register: __java_version_check

    - name: 'The Java version output'
      ansible.builtin.debug:
        var: __java_version_check.stdout_lines[0]
